

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: med_db
      POSTGRES_USER: med_user
      POSTGRES_PASSWORD: P0lsha
    ports:
      - "15432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql

  web:
    build:
      context: .
    container_name: django_app
#    command: ./wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./medical:/app/medical
      - ./wait-for-it.sh:/app/wait-for-it.sh
      - ./.flake8:/app/.flake8
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://med_user:P0lsha@db:5432/med_db
    command: >
      sh -c "
      chmod +x /app/wait-for-it.sh &&
      /app/wait-for-it.sh db:5432 -- 
      pip install --no-cache-dir -r /app/requirements.txt &&
      python /app/medical/manage.py migrate &&
      python /app/medical/manage.py runserver 0.0.0.0:8000
      "